### ISSUE TITLE
onClose()-hook is triggert when calender is closed via cancel-button

### ISSUE THREAD

**Issue by louis123562** [mikecoj/MCDatepicker#27] opened 2021-05-18 16:03 UTC
Hey,

check this fiddle: https://jsfiddle.net/Marco_Wa09/0r2186av/13/

When i close the calendar via cancel-button on the left, the onClose() - hook is triggert as well as the onCancel() - hook.

Is it possible to change this behaviour? At the moment we do not know if it was closed regularly by picking a date or via cancel-button :(

**Comment by mikecoj** [comment] 2021-05-18 20:07
Hey,

it was intentionally designed to act like that, let me explain to you why:

There are 4 main hooks that are linked to 4 specific events or actions:

1) `onOpen()` hook - this hook is linked to the custom open event so every time the calendar appears (when using the `open()` method or by clicking on the linked input field) the calendar pops up and then the `onOpen()` hook does its job,

2) `onClose()` hook - think of it as an opposite of `onOpen()` hook, the provided callback is executed every time the calendar disappears (that may be caused by using the `close()` method or by clicking `Cancel`  or `OK` button)

3) `onSelect()` hook - the provided callback is executed only when the `OK` button is clicked,
4) `onCancel()` hook - the provided callback is executed only when the `Cancel` button is clicked.

Check out this example: https://jsfiddle.net/mike_cojocari/gmzfphx9/12/ 

You will notice that when you click on the `Open` button the `onOpen()` hook executes its callback, if you will click on the calendar `OK` button, the `onSelect()` hook does its job and after that `onClose()` hook executes its callback because the calendar disappears.

Same for calendar `Cancel` button: `onCancel()` hook executes its callback because you're clicking on it and after that `onClose()` callback because the calendar disappears.

You may be wondering, in which case only the `onClose()` hook is activated?

It's simple, when the calendar disappears but none of the calendar buttons were clicked, for example when using the `close()` method.

**Comment by louis123562** [comment] 2021-05-18 20:14
Thanks for the explanation, but the onClose hook is executed before the onCancel hook. Is this correct?

**Comment by mikecoj** [comment] 2021-05-18 20:28
And that's an issue, will fix it in the next update! 

Thank you for opening this issue!

**Comment by louis123562** [comment] 2021-05-18 20:31
Perfect - me and my team were confused and had yet not way to figure out, if it was closed regularly or by cancel button :)

Thank you Mike, we really appreciate your work 👍

**Comment by louis123562** [comment] 2021-05-21 15:00
I "minified" the b7f64a63d24bcf3ef15c02c8a0fb5488af808dbd via webpack (nice tool!) and it solves the issue :) great work!

**Comment by mikecoj** [comment] 2021-05-24 10:23
Perfect, thank you!!

**Comment by mikecoj** [comment] 2021-05-24 12:31
Hey, this issue is fixed in the new version, 
and it can be closed!

**Closed by mikecoj** 2021-05-24 12:31 UTC
