### ISSUE TITLE
customWeekDays not work

### ISSUE THREAD

**Issue by enricodeveloper** [mikecoj/MCDatepicker#80] opened 2022-06-18 09:07 UTC
customWeekDays: ['D', 'L', 'M', 'M', 'G', 'V', 'S'] for italian language not work

error: Cannot read properties of undefined (reading 'allowedYears')

**Comment by ashenshugarRET** [comment] 2022-06-18 09:49
Can you upload your code specifying the options for your datepicker?
If customWeekDays is not the last item in the list make sure you have a comma at the end if the line...

**Comment by enricodeveloper** [comment] 2022-06-18 09:57
> Can you upload your code specifying the options for your datepicker? If customWeekDays is not the last item in the list make sure you have a comma at the end if the line...


`<input id="cin" type="text" class="custom-select11" name="cin" />`


const myDatePicker = MCDatepicker.create({
        el: '#cin',
        autoClose: true,
        closeOnBlur: true,
        dateFormat: 'dd/mm/yyyy',
        minDate: new Date(yyyy, mm, gg),
        customWeekDays: ['D', 'L', 'M', 'M', 'G', 'V', 'S'],
        customMonths: [
            'Gennaio',
            'Febbraio',
            'Marzo',
            'Aprile',
            'Maggio',
            'Giugno',
            'Luglio',
            'Agosto',
            'Settembre',
            'Ottobre',
            'Novembre',
            'Dicembre'
        ]
    })

**Comment by ashenshugarRET** [comment] 2022-06-18 11:20
Thanks,

Can you try by using the full word for each day rather than a single letter?
Also have you declared yyyy, mm and gg as variables as minDate needs to refer to a specific date rather than date formatting?

**Comment by enricodeveloper** [comment] 2022-06-19 16:22
> Thanks,
> 
> Can you try by using the full word for each day rather than a single letter? Also have you declared yyyy, mm and gg as variables as minDate needs to refer to a specific date rather than date formatting?

I solved. Now I have another problem with
minDate: new Date (yyyy, mm, dd),

yyyy = 2022 - mm = 06 - dd = 19

the calendar starts with the following month


Thank you

**Comment by ashenshugarRET** [comment] 2022-06-19 17:01
OK, so that is caused by a peculiarity of how javascript handles dates (see: [https://javascript.info/date](https://javascript.info/date)), so in your example, you could create a string from your variables ie 
`dateString = yyyy + "-" + mm + "-" + dd;`
then use that for your minDate:
`minDate: new Date (dateString),`

or you could just subtract 1 from your mm value...

**Comment by enricodeveloper** [comment] 2022-06-19 19:14
> OK, so that is caused by a peculiarity of how javascript handles dates (see: https://javascript.info/date), so in your example, you could create a string from your variables ie `dateString = yyyy + "-" + mm + "-" + dd;` then use that for your minDate: `minDate: new Date (dateString),`
> 
> or you could just subtract 1 from your mm value...

Perfect

Thank you :)

**Comment by ashenshugarRET** [comment] 2022-06-21 18:13
If your problem has been solved could you close the issue?

**Closed as completed** 2022-06-21 19:04 UTC
